# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-04 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnaorder', '0051_auto_20190201_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab')),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.Service'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Submission'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('lab', 'code'), ('lab', 'name')]),
        ),
    ]
