# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-06 23:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0052_submission_completed'),
        ('billing', '0002_lineitem_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator]),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='dnaorder.Submission'),
        ),
        migrations.AlterUniqueTogether(
            name='lineitem',
            unique_together=set([('submission', 'service')]),
        ),
    ]
