version: "3.9"
services:
  web:
    build: .
    ports:
      - "8010:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app 
    environment:
      - VERSION=DOCKER
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  frontend:
    build: /home/adam/atom/submissions
    ports:
      - "8080:80"
    command: nginx -g daemon off;
    volumes:
      - /app
volumes:
  postgres_data:
