version: "1.1"
services:
  app:
    ports:
      - "9000:80"
    volumes:
      - .:/usr/src/app 
      - data_volume:/data
    environment:
      - VERSION=DOCKER
    env_file:
      - ./.env.dev
    build:
      context: .
      dockerfile: fullstack.Dockerfile
    tty: true
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
  data_volume:
