# Generated by Django 2.2.6 on 2022-05-17 22:18

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dnaorder.models


class Migration(migrations.Migration):

    replaces = [('dnaorder', '0001_initial'), ('dnaorder', '0002_auto_20180411_2059'), ('dnaorder', '0003_auto_20180413_1749'), ('dnaorder', '0004_auto_20180413_2129'), ('dnaorder', '0005_auto_20180417_2230'), ('dnaorder', '0006_submission_participants'), ('dnaorder', '0007_auto_20180425_2342'), ('dnaorder', '0008_auto_20180507_2116'), ('dnaorder', '0009_auto_20180507_2204'), ('dnaorder', '0010_auto_20180508_2230'), ('dnaorder', '0011_auto_20180509_1748'), ('dnaorder', '0012_auto_20180509_2134'), ('dnaorder', '0013_submission_submission_data'), ('dnaorder', '0014_auto_20180510_1858'), ('dnaorder', '0015_auto_20180515_0006'), ('dnaorder', '0016_auto_20180524_1132'), ('dnaorder', '0017_submissiontype_schema'), ('dnaorder', '0018_submissiontype_help'), ('dnaorder', '0019_submission_sample_schema'), ('dnaorder', '0020_auto_20180911_1141'), ('dnaorder', '0021_auto_20180911_1520'), ('dnaorder', '0022_auto_20181003_1053'), ('dnaorder', '0023_submissiontype_examples'), ('dnaorder', '0024_auto_20181018_1415'), ('dnaorder', '0025_contact'), ('dnaorder', '0026_auto_20181029_1105'), ('dnaorder', '0027_auto_20181029_1106'), ('dnaorder', '0028_auto_20181031_1305'), ('dnaorder', '0029_submissiontype_schema'), ('dnaorder', '0030_auto_20181102_1056'), ('dnaorder', '0031_auto_20181205_1327'), ('dnaorder', '0032_submissiontype_submission_help'), ('dnaorder', '0033_auto_20181214_1449'), ('dnaorder', '0034_auto_20181214_1509'), ('dnaorder', '0035_auto_20181221_1334'), ('dnaorder', '0036_auto_20181221_1335'), ('dnaorder', '0037_auto_20181221_1335'), ('dnaorder', '0038_submission_last_name'), ('dnaorder', '0039_submission_pi_last_name'), ('dnaorder', '0040_submissiontype_sort_order'), ('dnaorder', '0041_submissiontype_confirmation_email_text'), ('dnaorder', '0042_submission_confirmed'), ('dnaorder', '0043_auto_20190108_1453'), ('dnaorder', '0044_submission_payment'), ('dnaorder', '0045_auto_20190114_1149'), ('dnaorder', '0046_submissiontype_active'), ('dnaorder', '0047_auto_20190122_1028'), ('dnaorder', '0048_auto_20190128_1359'), ('dnaorder', '0049_auto_20190131_1610'), ('dnaorder', '0050_submissiontype_statuses'), ('dnaorder', '0051_auto_20190201_1505'), ('dnaorder', '0052_submission_completed'), ('dnaorder', '0053_auto_20190530_1548'), ('dnaorder', '0054_draft'), ('dnaorder', '0055_auto_20190610_1149'), ('dnaorder', '0056_prefixid_lab'), ('dnaorder', '0057_auto_20190610_1453'), ('dnaorder', '0058_submissiontype_lab'), ('dnaorder', '0059_auto_20190611_1213'), ('dnaorder', '0060_lab_email'), ('dnaorder', '0061_submission_comments'), ('dnaorder', '0062_lab_variables'), ('dnaorder', '0063_auto_20190823_1355'), ('dnaorder', '0064_auto_20190823_1403'), ('dnaorder', '0065_auto_20190830_1111'), ('dnaorder', '0066_auto_20190905_1133'), ('dnaorder', '0067_vocabulary_name'), ('dnaorder', '0068_auto_20190916_1328'), ('dnaorder', '0069_auto_20190920_1335'), ('dnaorder', '0070_auto_20191122_1455'), ('dnaorder', '0071_auto_20191125_1228'), ('dnaorder', '0072_auto_20191126_1329'), ('dnaorder', '0073_lab_statuses'), ('dnaorder', '0074_import'), ('dnaorder', '0075_import_created'), ('dnaorder', '0076_submission_import_url'), ('dnaorder', '0077_submission_import_data'), ('dnaorder', '0078_auto_20200203_1432'), ('dnaorder', '0079_remove_import_submission'), ('dnaorder', '0080_submission_import_request'), ('dnaorder', '0081_import_external_id'), ('dnaorder', '0082_auto_20200211_1128'), ('dnaorder', '0083_submission_warnings'), ('dnaorder', '0084_userprofile'), ('dnaorder', '0085_sample'), ('dnaorder', '0086_auto_20200313_1411'), ('dnaorder', '0087_auto_20200422_1324'), ('dnaorder', '0088_remove_submission_sra_data'), ('dnaorder', '0089_auto_20200529_1409'), ('dnaorder', '0090_lab_institution'), ('dnaorder', '0091_lab_slug'), ('dnaorder', '0092_auto_20200601_1002'), ('dnaorder', '0093_auto_20200601_1012'), ('dnaorder', '0094_auto_20200713_1552'), ('dnaorder', '0095_auto_20200730_1030'), ('dnaorder', '0096_auto_20200730_1721'), ('dnaorder', '0097_auto_20200813_1146'), ('dnaorder', '0098_auto_20200813_1147'), ('dnaorder', '0099_prefixid_num_digits'), ('dnaorder', '0100_submissiontype_default_id'), ('dnaorder', '0101_auto_20200814_1510'), ('dnaorder', '0102_auto_20200818_1119'), ('dnaorder', '0103_lab_submission_email_text'), ('dnaorder', '0104_institution_logo'), ('dnaorder', '0105_auto_20201022_1210'), ('dnaorder', '0106_lab_disabled'), ('dnaorder', '0107_auto_20201028_1141'), ('dnaorder', '0108_auto_20201028_1141'), ('dnaorder', '0109_auto_20201102_1631'), ('dnaorder', '0110_auto_20201102_1631'), ('dnaorder', '0111_auto_20210719_1617'), ('dnaorder', '0112_remove_lab_plugins'), ('dnaorder', '0113_lab_plugins')]

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(max_length=25, unique=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.CharField(max_length=20)),
                ('pi_name', models.CharField(max_length=50)),
                ('pi_email', models.EmailField(max_length=75)),
                ('institute', models.CharField(max_length=75)),
                ('sample_form', models.FileField(upload_to='')),
                ('sample_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sra_form', models.FileField(blank=True, null=True, upload_to='')),
                ('sra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('biocore', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['submitted'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_file_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=dnaorder.models.submission_file_path)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dnaorder.Submission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prefix', models.CharField(default='', max_length=15)),
                ('sample_identifier', models.CharField(default=b'sample_name', max_length=25)),
                ('exclude_fields', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample_schema', django.contrib.postgres.fields.jsonb.JSONField(default=dnaorder.models.default_schema, null=True)),
                ('sample_help', models.TextField(blank=True, null=True)),
                ('submission_schema', django.contrib.postgres.fields.jsonb.JSONField(default=dnaorder.models.default_schema, null=True)),
                ('submission_help', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('confirmation_text', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('statuses', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dnaorder.SubmissionType'),
        ),
        migrations.AddField(
            model_name='submission',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='sample_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='sample_form',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='sra_form',
        ),
        migrations.AddField(
            model_name='submission',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dnaorder.Submission')),
                ('first_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='pi_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='pi_name',
            new_name='pi_first_name',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='submission',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='pi_last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='payment',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('payment_type_id', models.CharField(max_length=30)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
                ('home_page', models.TextField(default='')),
                ('email', models.EmailField(default='dnatech@ucdavis.edu', max_length=254)),
                ('table_variables', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('submission_variables', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('users', models.ManyToManyField(related_name='labs', to=settings.AUTH_USER_MODEL)),
                ('submission_page', models.TextField(blank=True, default='')),
                ('statuses', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='internal_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('internal_id', 'lab')},
        ),
        migrations.AlterField(
            model_name='submission',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='next_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='submissiontype',
            unique_together={('lab', 'prefix')},
        ),
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('obj', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Vocabulary')),
            ],
            options={
                'ordering': ['vocabulary', 'value'],
                'unique_together': {('vocabulary', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('LOG', 'LOG'), ('NOTE', 'NOTE')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('sent', models.NullBooleanField()),
                ('public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Submission')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dnaorder.Note')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='sample_identifier',
            field=models.CharField(default='sample_name', max_length=25),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='internal_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='import_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='import_internal_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('api_url', models.URLField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('external_id', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='import_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='dnaorder.Import'),
        ),
        migrations.AddField(
            model_name='submission',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='samples_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='warnings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_suffix', models.PositiveIntegerField()),
                ('row', models.PositiveIntegerField()),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='dnaorder.Submission')),
            ],
            options={
                'unique_together': {('id_suffix', 'submission'), ('name', 'submission')},
            },
        ),
        migrations.RemoveField(
            model_name='submission',
            name='sra_data',
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
                ('logo', models.FileField(null=True, upload_to=dnaorder.models.logo_file_path)),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dnaorder.Institution'),
        ),
        migrations.AddField(
            model_name='lab',
            name='identifier',
            field=models.SlugField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('institution', 'identifier')},
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='identifier',
            new_name='lab_id',
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('institution', 'lab_id')},
        ),
        migrations.AddField(
            model_name='submission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='_submission_participants_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_types', to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dnaorder.Lab'),
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('validated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='lab',
            name='site',
        ),
        migrations.CreateModel(
            name='ProjectID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=15)),
                ('next_id', models.PositiveIntegerField(default=0)),
                ('lab', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='dnaorder.Lab')),
                ('num_digits', models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                'unique_together': {('lab', 'prefix')},
                'ordering': ('lab', 'prefix'),
            },
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='default_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnaorder.ProjectID'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='prefix',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='submission_email_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='default_participants',
            field=models.ManyToManyField(blank=True, related_name='default_participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Submitted', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Submitted', max_length=50),
        ),
        migrations.CreateModel(
            name='InstitutionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGE', 'Manage')], max_length=10)),
                ('permission_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dnaorder.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('ADMIN', 'Lab administrator'), ('MEMBER', 'Lab member'), ('ASSOCIATE', 'Lab associate')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dnaorder.Lab')),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='plugins',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
