# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 19:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import dnaorder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.CharField(max_length=20)),
                ('pi_name', models.CharField(max_length=50)),
                ('pi_email', models.EmailField(max_length=75)),
                ('institute', models.CharField(max_length=75)),
                ('sample_form', models.FileField(upload_to=dnaorder.models.sample_form_path)),
                ('sample_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sra_form', models.FileField(blank=True, null=True, upload_to=dnaorder.models.sra_samples_path)),
                ('sra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['submitted'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('form', models.FileField(upload_to=b'submission_forms/')),
                ('header_index', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('skip_rows', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('start_column', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('end_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sample_identifier', models.CharField(default=b'sample_name', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=30)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('regex', models.CharField(blank=True, max_length=250, null=True)),
                ('choices', models.TextField(blank=True, null=True)),
                ('range', django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.SubmissionType'),
        ),
    ]
