# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.CharField(max_length=20)),
                ('pi_name', models.CharField(max_length=50)),
                ('pi_email', models.EmailField(max_length=75)),
                ('institute', models.CharField(max_length=75)),
                ('form', models.FileField(upload_to=b'submissions/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('form', models.FileField(upload_to=b'submission_forms/')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.SubmissionType'),
        ),
    ]
