# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 19:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import dnaorder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[(b'LOG', b'LOG'), (b'NOTE', b'NOTE')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('sent', models.NullBooleanField()),
                ('public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(max_length=25, unique=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.CharField(max_length=20)),
                ('pi_name', models.CharField(max_length=50)),
                ('pi_email', models.EmailField(max_length=75)),
                ('institute', models.CharField(max_length=75)),
                ('sample_form', models.FileField(upload_to=dnaorder.models.sample_form_path)),
                ('sample_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sra_form', models.FileField(blank=True, null=True, upload_to=dnaorder.models.sra_samples_path)),
                ('sra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('biocore', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['submitted'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_file_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=dnaorder.models.submission_file_path)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dnaorder.Submission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Submission Statuses',
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('form', models.FileField(upload_to=b'submission_forms/')),
                ('header_index', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('skip_rows', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('start_column', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('end_column', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sample_identifier', models.CharField(default=b'sample_name', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=30)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('regex', models.CharField(blank=True, max_length=250, null=True)),
                ('choices', models.TextField(blank=True, null=True)),
                ('range', django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.SubmissionStatus'),
        ),
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.SubmissionType'),
        ),
        migrations.AddField(
            model_name='note',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Submission'),
        ),
    ]
