# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionstatus',
            old_name='default',
            new_name='auto_lock',
        ),
        migrations.AddField(
            model_name='submission',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
