# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='data_index',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='header_index',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='offset',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sample_form',
            field=models.FileField(upload_to=dnaorder.models.sample_form_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sra_form',
            field=models.FileField(upload_to=dnaorder.models.sra_samples_path),
        ),
    ]
