# Generated by Django 2.2.28 on 2022-11-18 17:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0001_squashed_0113_lab_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='plugin_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
