# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0002_auto_20180216_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontype',
            old_name='offset',
            new_name='start_column',
        ),
    ]
