# Generated by Django 3.2.16 on 2023-01-27 19:30

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0002_auto_20221118_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='plugins',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='import',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='projectid',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='dnaorder.lab'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
