# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0002_auto_20180411_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Note'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnaorder.SubmissionStatus'),
        ),
    ]
