# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0002_submissionfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionfile',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='submission',
            name='biocore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dnaorder.Submission'),
        ),
    ]
