# Generated by Django 3.2.16 on 2023-02-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0003_auto_20230127_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='home_page',
            field=models.TextField(default=''),
        ),
    ]
