# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0003_auto_20180216_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='end_column',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
