# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0003_auto_20180309_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.SubmissionStatus'),
        ),
    ]
