# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0004_submissiontype_end_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sample_identifier',
            field=models.CharField(default=b'sample_name', max_length=25),
        ),
    ]
