# Generated by Django 3.2.16 on 2023-04-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0004_institution_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='pi_last_name',
            field=models.CharField(max_length=75),
        ),
    ]
