# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0004_auto_20180309_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionstatus',
            options={'ordering': ['order'], 'verbose_name_plural': 'Submission Statuses'},
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
