# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0004_auto_20180413_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontype',
            name='end_column',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='start_column',
            field=models.CharField(default=b'A', max_length=2),
        ),
    ]
