# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0005_auto_20180314_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionfile',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='id',
            field=models.CharField(default=dnaorder.models.generate_file_id, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
