# Generated by Django 3.2.25 on 2025-08-14 19:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0005_alter_submission_pi_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('lead', 'lead'), ('watcher', 'watcher')], max_length=15), blank=True, default=list, size=None)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='temp_participants')),
            ],
            options={
                'unique_together': {('submission', 'user')},
            },
        ),
    ]
