# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0005_auto_20180417_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
