# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0006_auto_20180216_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontype',
            old_name='data_index',
            new_name='skip_rows',
        ),
    ]
