# Generated by Django 3.2.25 on 2025-08-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0007_migrate_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='participants',
            new_name='old_participants',
        ),
    ]
