# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0006_auto_20180315_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='prefix',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
