# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0007_auto_20180217_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sra_form',
            field=models.FileField(blank=True, null=True, upload_to=dnaorder.models.sra_samples_path),
        ),
    ]
