# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0007_submissiontype_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='internal_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
