# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0007_auto_20180425_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='has_submission_fields',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='submission_end_column',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='submission_header_index',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='submission_skip_rows',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='submission_start_column',
            field=models.CharField(blank=True, default=b'A', max_length=2, null=True),
        ),
    ]
