# Generated by Django 3.2.25 on 2025-08-14 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0007_2_rename_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating', through='dnaorder.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
