# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 22:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0008_auto_20180220_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sample_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='sra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
