# Generated by Django 4.2.23 on 2025-10-07 23:26

from django.db import migrations, models
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0008_auto_20250814_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='import',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='plugins',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='lab',
            name='plugins',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='lab',
            name='statuses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='lab',
            name='submission_variables',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='lab',
            name='table_variables',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='note',
            name='sent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='import_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='payment',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='plugin_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sample_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sample_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='warnings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='sample_schema',
            field=models.JSONField(default=dnaorder.models.default_schema, null=True),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='statuses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='submission_schema',
            field=models.JSONField(default=dnaorder.models.default_schema, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='obj',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
