# Generated by Django 4.2.23 on 2025-10-07 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0009_remove_submission_old_participants_alter_draft_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meta', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PI',
            fields=[
                ('email', models.EmailField(max_length=75, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dnaorder.piinstitution')),
            ],
        ),
    ]
