# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0009_auto_20180507_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.SubmissionType'),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
