# Generated by Django 4.2.26 on 2025-11-15 00:14

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# dnaorder.migrations.0016_remove_submission_pi_alter_pi_email_alter_pi_id

class Migration(migrations.Migration):

    replaces = [('dnaorder', '0010_piinstitution_remove_submission_old_participants_pi'), ('dnaorder', '0011_submission_pi'), ('dnaorder', '0012_pi_department'), ('dnaorder', '0013_unique_institution_name'), ('dnaorder', '0014_alter_pi_department_alter_piinstitution_name'), ('dnaorder', '0015_pi_id_alter_pi_email'), ('dnaorder', '0016_remove_submission_pi_alter_pi_email_alter_pi_id'), ('dnaorder', '0017_submission_pi')]

    dependencies = [
        ('dnaorder', '0009_remove_submission_old_participants_alter_draft_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('meta', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PI',
            fields=[
                ('email', models.EmailField(max_length=75, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=75, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dnaorder.piinstitution')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        # migrations.AlterField(
        #     model_name='pi',
        #     name='email',
        #     field=models.EmailField(max_length=75, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='pi',
        #     name='id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        migrations.AddField(
            model_name='submission',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnaorder.pi'),
        ),
    ]
