# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dnaorder.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0009_auto_20180321_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[(b'LOG', b'LOG'), (b'NOTE', b'NOTE')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('emails', dnaorder.fields.EmailListField(max_length=200, null=True)),
                ('sent', models.NullBooleanField()),
                ('public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Submission')),
            ],
        ),
    ]
