# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0009_auto_20180220_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=30)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('regex', models.CharField(blank=True, max_length=250, null=True)),
                ('choices', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['submitted']},
        ),
    ]
