# Generated by Django 4.2.23 on 2025-10-07 23:55

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0010_piinstitution_remove_submission_old_participants_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnaorder.pi'),
        ),
    ]
