# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0010_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='emails',
        ),
    ]
