# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0010_auto_20180221_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(default=dnaorder.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
