# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0010_auto_20180508_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descendants', to='dnaorder.SubmissionType'),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dnaorder.SubmissionType'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
