# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0011_auto_20180509_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dnaorder.SubmissionType'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='dnaorder.SubmissionType'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
