# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 18:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0011_auto_20180328_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
