# Generated by Django 4.2.23 on 2025-10-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0011_submission_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
