# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 18:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0011_auto_20180224_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='range',
            field=django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, null=True),
        ),
    ]
