# Generated by Django 4.2.23 on 2025-10-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0012_pi_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piinstitution',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
