# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 17:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0012_auto_20180509_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
