# Generated by Django 4.2.23 on 2025-10-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0013_unique_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='department',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='piinstitution',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
