# Generated by Django 4.2.26 on 2025-11-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0014_alter_pi_department_alter_piinstitution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='email',
            field=models.EmailField(max_length=75, primary_key=True, serialize=False, unique=True),
        ),
    ]
