# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0014_auto_20180510_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='payment_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='payment_type',
            field=models.CharField(choices=[(b'DaFIS', b'DaFIS'), (b'Credit Card', b'Credit Card')], default='DaFIS', max_length=50),
            preserve_default=False,
        ),
    ]
