# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 18:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0015_auto_20180515_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='payment_type',
            field=models.CharField(choices=[(b'DaFIS', b'DaFIS (UC Davis Account String)'), (b'UC Chart String', b'UC Chart String'), (b'Credit Card', b'Credit Card'), (b'Purchase Order', b'Purchase Order'), (b'Check', b'Check'), (b'Wire Transfer', b'Wire Transfer')], max_length=50),
        ),
    ]
