# Generated by Django 4.2.26 on 2025-11-14 22:48

from django.db import migrations, models

def populate_id(apps, schema_editor):
    PI = apps.get_model('dnaorder', 'PI')
    for i, obj in enumerate(PI.objects.all(), start=1):
        obj.id = i
        obj.save(update_fields=['id'])

class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0015_pi_id_alter_pi_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='pi',
        ),
        migrations.RunPython(populate_id),
        migrations.AlterField(
            model_name='pi',
            name='email',
            field=models.EmailField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]