# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 21:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0016_auto_20180524_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
