# Generated by Django 4.2.26 on 2025-11-14 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0016_remove_submission_pi_alter_pi_email_alter_pi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnaorder.pi'),
        ),
    ]
