# Generated by Django 5.2.15 on 2026-09-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0010_piinstitution_remove_submission_old_participants_pi_squashed_0017_submission_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='internal',
            field=models.BooleanField(default=False, help_text='Internal types may only be used by lab members to create/update submissions.'),
        ),
    ]
