# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0017_submissiontype_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='help',
            field=models.TextField(blank=True, null=True),
        ),
    ]
