# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-11 18:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0019_submission_sample_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sample_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
