# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0021_auto_20180911_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dnaorder.SubmissionType'),
        ),
    ]
