# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 18:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0022_auto_20181003_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='examples',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
