# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-19 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0024_auto_20181018_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dnaorder.Submission')),
            ],
        ),
    ]
