# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0025_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='last_name',
        ),
    ]
