# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0027_auto_20181029_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontype',
            old_name='schema',
            new_name='sample_schema',
        ),
    ]
