# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 17:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0029_submissiontype_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='sample_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dnaorder.models.default_schema, null=True),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dnaorder.models.default_schema, null=True),
        ),
    ]
