# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-05 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0030_auto_20181102_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontype',
            old_name='help',
            new_name='sample_help',
        ),
    ]
