# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0033_auto_20181214_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontype',
            old_name='schema',
            new_name='submission_schema',
        ),
    ]
