# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0034_auto_20181214_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissiontype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='submission',
            name='pi_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
