# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0038_submission_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pi_last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
