# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-03 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0039_submission_pi_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='sort_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
