# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0040_submissiontype_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='confirmation_email_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
