# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0041_submissiontype_confirmation_email_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
