# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-08 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0042_submission_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontype',
            old_name='confirmation_email_text',
            new_name='confirmation_text',
        ),
    ]
