# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-09 23:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0043_auto_20190108_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='payment',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
