# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('dnaorder', '0046_submissiontype_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('payment_type_id', models.CharField(choices=[(b'UCDPaymentType', b'UC Davis Payment')], max_length=30)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AlterModelOptions(
            name='submissiontype',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='submissiontype',
            name='examples',
        ),
    ]
