# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0048_auto_20190128_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefixID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=15)),
                ('current_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='prefix',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
