# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 22:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0049_auto_20190131_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='statuses',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
