# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0050_submissiontype_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
