# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0051_auto_20190201_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
