# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-04 16:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0053_auto_20190530_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
