# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0054_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='internal_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('internal_id', 'lab')]),
        ),
    ]
