# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-10 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0055_auto_20190610_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefixid',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
        ),
    ]
