# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-10 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0056_prefixid_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefixid',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
            preserve_default=False,
        ),
    ]
