# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-10 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0057_auto_20190610_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
            preserve_default=False,
        ),
    ]
