# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0058_submissiontype_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='next_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='submissiontype',
            unique_together=set([('lab', 'prefix')]),
        ),
    ]
