# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-21 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0060_lab_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
