# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-23 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0062_lab_variables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='variables',
            new_name='samples_variables',
        ),
        migrations.AddField(
            model_name='lab',
            name='submission_variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
