# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-23 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0063_auto_20190823_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='samples_variables',
            new_name='sample_variables',
        ),
    ]
