# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-30 18:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0064_auto_20190823_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('obj', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'ordering': ['vocabulary', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Vocabulary'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([('vocabulary', 'value')]),
        ),
    ]
