# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0066_auto_20190905_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
