# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-16 20:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0067_vocabulary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='default_participants',
            field=models.ManyToManyField(related_name='_submissiontype_default_participants_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='term',
            name='obj',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
