# Generated by Django 2.2.6 on 2019-11-22 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0069_auto_20190920_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='submission_page',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lab',
            name='home_page',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lab',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dnaorder.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('LOG', 'LOG'), ('NOTE', 'NOTE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='sample_identifier',
            field=models.CharField(default='sample_name', max_length=25),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
