# Generated by Django 2.2.6 on 2019-11-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0070_auto_20191122_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='internal_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
