# Generated by Django 2.2.6 on 2019-11-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0071_auto_20191125_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='submission_page',
            field=models.TextField(blank=True, default=''),
        ),
    ]
