# Generated by Django 2.2.6 on 2019-11-26 21:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0072_auto_20191126_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='statuses',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
