# Generated by Django 2.2.6 on 2020-01-29 20:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0073_lab_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.CharField(default=dnaorder.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('api_url', models.URLField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Submission')),
            ],
        ),
    ]
