# Generated by Django 2.2.6 on 2020-01-29 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0074_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
