# Generated by Django 2.2.6 on 2020-02-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0075_import_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='import_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
