# Generated by Django 2.2.6 on 2020-02-03 21:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0076_submission_import_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='import_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
