# Generated by Django 2.2.6 on 2020-02-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0077_submission_import_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='import_url',
        ),
        migrations.AddField(
            model_name='submission',
            name='import_internal_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
