# Generated by Django 2.2.6 on 2020-02-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0078_auto_20200203_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='submission',
        ),
    ]
