# Generated by Django 2.2.6 on 2020-02-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0079_remove_import_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='import_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='dnaorder.Import'),
        ),
    ]
