# Generated by Django 2.2.6 on 2020-02-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0080_submission_import_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='external_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
