# Generated by Django 2.2.6 on 2020-02-11 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0081_import_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='samples_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
