# Generated by Django 2.2.6 on 2020-03-05 18:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0082_auto_20200211_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='warnings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
