# Generated by Django 2.2.6 on 2020-03-12 22:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0084_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_suffix', models.PositiveIntegerField()),
                ('row', models.PositiveIntegerField()),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='dnaorder.Submission')),
            ],
            options={
                'unique_together': {('id_suffix', 'submission'), ('row', 'submission'), ('name', 'submission')},
            },
        ),
    ]
