# Generated by Django 2.2.6 on 2020-04-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0086_auto_20200313_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='sample_variables',
            new_name='table_variables',
        ),
    ]
