# Generated by Django 2.2.6 on 2020-05-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0087_auto_20200422_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='sra_data',
        ),
    ]
