# Generated by Django 2.2.6 on 2020-05-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0089_auto_20200529_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dnaorder.Institution'),
        ),
    ]
