# Generated by Django 2.2.6 on 2020-06-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0090_lab_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
