# Generated by Django 2.2.6 on 2020-06-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0091_lab_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='slug',
            new_name='identifier',
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('institution', 'identifier')},
        ),
    ]
