# Generated by Django 2.2.6 on 2020-06-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0092_auto_20200601_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='identifier',
            new_name='lab_id',
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('institution', 'lab_id')},
        ),
    ]
