# Generated by Django 2.2.6 on 2020-07-13 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnaorder', '0093_auto_20200601_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='_submission_participants_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_types', to='dnaorder.Lab'),
        ),
        migrations.CreateModel(
            name='LabPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('admin', 'Admin'), ('manage_types', 'Manage submission types'), ('manage_submissions', 'Manage submissions')], max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('admin', 'Admin'), ('manage', 'Manage')], max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
