# Generated by Django 2.2.6 on 2020-07-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0095_auto_20200730_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='validated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
