# Generated by Django 2.2.6 on 2020-08-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0096_auto_20200730_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='site',
        ),
        migrations.AlterField(
            model_name='prefixid',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='dnaorder.Lab'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='prefixid',
            unique_together={('lab', 'prefix')},
        ),
    ]
