# Generated by Django 2.2.6 on 2020-08-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0097_auto_20200813_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefixid',
            old_name='current_id',
            new_name='next_id',
        ),
    ]
