# Generated by Django 2.2.6 on 2020-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0098_auto_20200813_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefixid',
            name='num_digits',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
