# Generated by Django 2.2.6 on 2020-08-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0100_submissiontype_default_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrefixID',
            new_name='ProjectID',
        ),
    ]
