# Generated by Django 2.2.6 on 2020-09-18 17:40

from django.db import migrations, models
import dnaorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0103_lab_submission_email_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.FileField(null=True, upload_to=dnaorder.models.logo_file_path),
        ),
    ]
