# Generated by Django 2.2.6 on 2020-10-22 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0104_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontype',
            name='default_participants',
            field=models.ManyToManyField(blank=True, related_name='default_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
