# Generated by Django 2.2.6 on 2020-10-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0105_auto_20201022_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
