# Generated by Django 2.2.6 on 2020-11-03 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0108_auto_20201028_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionpermission',
            old_name='institution',
            new_name='permission_object',
        ),
        migrations.RemoveField(
            model_name='labpermission',
            name='institution',
        ),
        migrations.AddField(
            model_name='labpermission',
            name='permission_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='labpermission',
            name='permission',
            field=models.CharField(choices=[('admin', 'Lab administrator'), ('member', 'Lab member'), ('associate', 'Lab associate')], max_length=10),
        ),
    ]
