# Generated by Django 2.2.6 on 2020-11-03 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0109_auto_20201102_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpermission',
            name='permission_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Lab'),
        ),
    ]
