# Generated by Django 2.2.6 on 2021-07-19 23:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0110_auto_20201102_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='plugins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bioshare', 'bioshare')], max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='institutionpermission',
            name='permission',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGE', 'Manage')], max_length=10),
        ),
        migrations.AlterField(
            model_name='institutionpermission',
            name='permission_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dnaorder.Institution'),
        ),
        migrations.AlterField(
            model_name='labpermission',
            name='permission',
            field=models.CharField(choices=[('ADMIN', 'Lab administrator'), ('MEMBER', 'Lab member'), ('ASSOCIATE', 'Lab associate')], max_length=10),
        ),
        migrations.AlterField(
            model_name='labpermission',
            name='permission_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dnaorder.Lab'),
        ),
        migrations.AlterField(
            model_name='labpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
