# Generated by Django 2.2.6 on 2021-07-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0111_auto_20210719_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='plugins',
        ),
    ]
