# Generated by Django 2.2.6 on 2021-07-21 18:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnaorder', '0112_remove_lab_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='plugins',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
